name: Laravel AI Dev Agent (Groq)

on:
  push:
    branches: [ "main", "master", "dev" ]

jobs:
  ai_review:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # حدثنا النسخة لتجنب التحذيرات

      - name: Install Dependencies
        run: pip install openai requests

      - name: Run AI Agent
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_SHA: ${{ github.sha }}
          REPO_NAME: ${{ github.repository }}
        run: |
          FILE_PATH=$(find . -name "ai_agent.py" | head -n 1)
          python "$FILE_PATH"

      - name: Upload Review File
        uses: actions/upload-artifact@v4
        with:
          name: ai-code-review
          path: ai_review.md
